export default function get_data() {
return (<div>
 <h1>JOLLY MANIFESTO</h1>
<p>THE JOLLY MANIFESTO</p>
<p>THE JOLLY MANIFESTO</p>
<p>THE JOLLY MANIFESTO</p>
<p>THE JOLLY MANIFESTO</p>
<p>THE JOLLY MANIFESTO</p>
<p>THE JOLLY MANIFESTO</p>
<p>THE JOLLY MANIFESTO</p>
<p>THE JOLLY MANIFESTO</p>
<p>THE JOLLY MANIFESTO</p>
<p>THE JOLLY MANIFESTO</p>
<p>THE JOLLY MANIFESTO</p>
<p>THE JOLLY MANIFESTO</p>
<p>THE JOLLY MANIFESTO</p>
<p>THE JOLLY MANIFESTO</p>
<p>THE JOLLY MANIFESTO</p>
<p>THE JOLLY MANIFESTO</p>
</div>);
}
